server:
  port: 80


spring:
  application:
    name: cloud-order-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://192.168.0.42:7001/eureka/