server:
  port: 7001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #不把自己注册到注册中心
    fetch-registry: false #不需要检索服务
    service-url:
      defaultZoneL: http://${eureka.instance.hostname}:${server.port}/eureka/
