server:
  port: 83

spring:
  application:
#    name: nacos-order-provider
      name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #注册到nacos注册中心
    sentinel:
        transport:
          dashboard: localhost:8080 #配置sentinel服务熔断服务
          port: 8719

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true